# Generated by Django 4.2 on 2023-08-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='a_type',
            field=models.CharField(choices=[('PERMANENT', 'PERMANENT'), ('CURRENT', 'CURRENT')], default='PERMANENT', max_length=25),
        ),
    ]
